---
- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    lock_timeout: 600
    name: prometheus-node-exporter
    state: present

- name: Enable and start node_exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
